name: Run Daily Collection
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run Collection Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DEEPL_API_KEY: ${{secrets.DEEPL_API_KEY}}
        run: python collect_daily_information.py

      - name: Get Date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily report."
          file_pattern: 'reports/*.md'

      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: üåê Global Tech Briefing - ${{ env.DATE }}
          content-filepath: ./reports/Daily_Briefing_${{ env.DATE }}_EN.md
          labels: 
            daily-report
            automated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
